### ISSUE TITLE
(BUG) found in  DailyPrayer-Android Other apps are not open

### ISSUE THREAD

**Issue by saraji-ali** [robertoissc/DailyPrayer-Android#25]
# Project Information

* Repository:  https://github.com/robertoissc/DailyPrayer-Android
* Project Name: DailyPrayer-Android

# Expected behavior

When I click on other apps, a new application should open the Google Play Store

# Actual behavior

When I click on other apps, no further releases appear

# How to reproduce

1-[Download](https://play.google.com/store/apps/details?id=com.isscroberto.dailyprayerandroid) the app and open it
2-Click on the Settings button
3- try to open any other app
4-see bug 

* Browser/App version:  Current Version 18.10.01
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# My Github Account
https://github.com/facebook-786

**Comment by roberto-o-r** [comment]
Hi @saraji-ali!
Tested and confirmed, the fix will be included with next version. Thank you for the report!
